[build-system]
requires = ["setuptools"]  # greater than version 61 invludes non-python files 
build-backend = "setuptools.build_meta" 


                                       
[project]
name = "katsdpcal"
description = "MeerKAT calibration pipeline"
readme = "README.md"
requires-python = ">=3.6"
license = {file = "LICENSE"}
keywords = ["kat", "kat7", "meerkat", "ska"]
authors = [
    {name = "MeerKAT SDP Team", email = "sdpdev+katsdpcal@ska.ac.za"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: Astronomy",
]

dynamic = ["version"]
# remove the dependcies that were tied down to be very specific, we should leave lose requirements, like it should just import katdal and not clone the repo
dependencies = [
    "numpy>=1.15",
    "scipy>=1.5.0", 
    "numba>=0.49.0",
    "dask[array,distributed]>=1.1.0",
    "distributed>=2.2.0",
    "bokeh",
    "attrs",
    "sortedcontainers",
    "aiokatcp",
    "astropy",
    "async_timeout>=1.4.0",
    "importlib-resources; python_version<'3.9'",
    "katpoint @ git+https://github.com/ska-sa/katpoint",
    "katdal @ git+https://github.com/ska-sa/katdal", 
    "katsdpcalproc @ git+https://github.com/ska-sa/katsdpcalproc",
    "katsdpmodels[requests] @ git+https://github.com/ska-sa/katsdpmodels",
    "katsdptelstate @ git+https://github.com/ska-sa/katsdptelstate",
    "katsdpservices[argparse,aiomonitor] @ git+https://github.com/ska-sa/katsdpservices",
    "katsdpsigproc @ git+https://github.com/ska-sa/katsdpsigproc",
    "spead2>=3.0.0",
    "docutils",
    "matplotlib>=2",
    "jsonschema"
]

# create project scripts table to make the scripts exceutable