[build-system]
requires = ["setuptools>=64", "versioningit"] 
build-backend = "setuptools.build_meta" 


                                       
[project]
name = "katsdpcal"
description = "MeerKAT calibration pipeline"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
keywords = ["kat", "kat7", "meerkat", "ska"]
authors = [
    {name = "MeerKAT SDP Team", email = "sdpdev+katsdpcal@ska.ac.za"}
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: Astronomy",
]

dynamic = ["version"]

dependencies = [
    "aiokatcp",
    "astropy",
    "async_timeout>=1.4.0",
    "attrs",
    "bokeh",
    "dask[array,distributed]>=1.1.0",
    "distributed>=2.2.0",
    "docutils",
    "importlib-resources; python_version < \"3.9\"",
    "jsonschema",
    "katdal",
    "katpoint",
    "katsdpcalproc",
    "katsdpmodels[requests]",
    "katsdpservices[argparse,aiomonitor]",
    "katsdpsigproc",
    "katsdptelstate",
    "matplotlib>=2",
    "numba>=0.49.0",
    "numpy>=1.15",
    "scipy>=1.5.0",
    "sortedcontainers",
    "spead2>=3.0.0",
]

[tool.versioningit.vcs]
method = "git"
match = ["v*"]
# Set a default tag for versioningit when no matching tags are found.
default-tag = "v0.0.0"

[tool.versioningit.format]
distance =       "{base_version}.post1.dev{distance}+{branch}.{vcs}{rev}"
distance-dirty = "{base_version}.post1.dev{distance}+{branch}.{vcs}{rev}.dirty"
dirty =          "{base_version}+dirty"

[project.scripts]
run_cal = "katsdpcal.scripts.run_cal:main"
sim_ts = "katsdpcal.scripts.sim_ts:main_sync"
sim_data_stream = "katsdpcal.scripts.sim_data_stream:main_sync"
create_test_data = "katsdpcal.scripts.create_test_data:main"


